server {

    listen 80;

    root /usr/share/nginx/html;

    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/users {
        proxy_pass http://userservice:8081;
    }

    location /api/products {
        proxy_pass http://productservice:8082;
    }

    location /api/orders {
        proxy_pass http://orderservice:8083;
    }
}
